services:
  - type: web
    name: andescendants
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server/cloud.mjs
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
